### PR TITLE
Packagining for PyPI/pip deployment

### LINKED ISSUE #25: Remove hardcoded paths and use envs for paths to data

### LINKED ISSUE #29: Test PyPI/pip packaging

### PR DESCRIPTION
**Pull request by bakhtos**
- Files necessary for packaging added (`pyproject.toml`, `MANIFEST.in`)
- Some imports are now lazy imports (like `matplotlib`)
- All demos and tests assume that `loglead` package is installed and that `env` file is used to point to data
- The two demos that depend on `samples` data are refactored:
    - `samples` dir is moved to `demos`
    - demo scripts handle paths with `os.path.join`
- Fixes #25 
- Fixes #29 

I managed to run the two `samples` demos using this pip installation.

### CODE REVIEW

**Comment by bakhtos** [comment]
```
python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ loglead
```

```
python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ loglead[bert,test,demo]
```

**Comment by bakhtos** [comment]
@mmantyla @jnyyssol @yuqwang Please check the `pyproject.toml` file for the following metadata:

- Do you want to use Helsinki emails?
- Are the keywords ok?
- Do you want to use the same README for the page on pypi or should we make another one?
- Are the classifiers fine? The full list is [here](https://pypi.org/classifiers/)

**Comment by jnyyssol** [comment]
> * Do you want to use Helsinki emails?

Yes, they are fine.

> * Are the keywords ok?

Fix typo on "anomanly detection".

> * Do you want to use the same README for the page on pypi or should we make another one?

The existing works, but update details (e.g. tags) and fix image (or remove).

> * Are the classifiers fine? The full list is [here](https://pypi.org/classifiers/)

Use "beta" instead of "production" as development status classifier

**Comment by bakhtos** [comment]
> The existing works, but update details (e.g. tags) and fix image (or remove).

What do you mean by tags in the README.md?

**Comment by jnyyssol** [comment]
> What do you mean by tags in the README.md?

The optional dependencies that are not used anymore, but are in the readme in: https://test.pypi.org/project/LogLead/
But yeah, naturally those should be removed from both readmes.

**Comment by bakhtos** [comment]
Hello! 

I implemented the changes to the metadata and merged with Mika's changes to test/demo files.

The version 0.0.9 on TestPyPI should be the 'final' one for this stage.

Please install and test one last time the test/demo files (they do not use `LOGLEAD_PATH` and assume `loglead` is installed).

```
python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ loglead==0.0.9```

**Comment by mmantyla** [comment]
Good news. HDFS_samples.py  TB_samples.py work OK. 
However, both ano_detection.py and parsing_speed.py fail as they rely on LOGLEAD_PATH to find their config file. Config file determines what is run on these tests. 

`(LL_test_pip4) mmantyla@lh3-523-29052:~/Alex4_LL_pip/LogLead/demo/parser_benchmark$ python ano_detection.py
/home/mmantyla/Alex4_LL_pip/LogLead/demo/parser_benchmark
Traceback (most recent call last):
  File "/home/mmantyla/Alex4_LL_pip/LogLead/demo/parser_benchmark/ano_detection.py", line 29, in <module>
    default_config = LOGLEAD_PATH + '/demo/parser_benchmark/ano_detection_config.yml'
                     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
(LL_test_pip4) mmantyla@lh3-523-29052:~/Alex4_LL_pip/LogLead/demo/parser_benchmark$ ls
ano_detection.py  ano_detection_config.yml  parsing_speed.py  speed_config.yml
(LL_test_pip4) mmantyla@lh3-523-29052:~/Alex4_LL_pip/LogLead/demo/parser_benchmark$ python parsing_speed.py
None
Traceback (most recent call last):
  File "/home/mmantyla/Alex4_LL_pip/LogLead/demo/parser_benchmark/parsing_speed.py", line 25, in <module>
    default_config = LOGLEAD_PATH + '/demo/parser_benchmark/speed_config.yml'
                     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`

**Pull request merged**
